### ISSUE TITLE
[BTA-02M] Improper Assumption of Calldata

### ISSUE THREAD

**Issue by galimba** [NexeraProtocol/NexeraIDSigGatingContracts#71]
## BTA-02M: Improper Assumption of Calldata

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Logical Fault](/appendix/finding-types#logical-fault) | <img class="o-severity o-medium" src="https://omniscia.io/report-assets/medium.png" /> | [BaseTxAuthDataVerifier.sol:L119](https://github.com/NexeraProtocol/NexeraIDSigGatingContracts/blob/5a2cdebe6cd8dbd1369dfda8550bed19cbd2f59e/sig-gating-contracts/contracts/sigVerifiers/BaseTxAuthDataVerifier.sol#L119), [L122-L123](https://github.com/NexeraProtocol/NexeraIDSigGatingContracts/blob/5a2cdebe6cd8dbd1369dfda8550bed19cbd2f59e/sig-gating-contracts/contracts/sigVerifiers/BaseTxAuthDataVerifier.sol#L122-L123) |

### Description:

The `BaseTxAuthDataVerifier` signature verifier system expects the top-level function call **to correctly specify the signature as the last argument of its function** and **to mutate its function signature to accommodate for the `_signature` payload**.

Both of these assumptions significantly hamper the applicability of the `BaseTxAuthDataVerifier` due to non-compliancy of EIP function signatures and render it prone to errors, as introducing the signature to any location other than the end of the function's calldata will result in verifications failing.

Additionally, multiple dynamic arguments will be packed in calldata differently, causing the fixed `_SIGNATURE_OFFSET` reduction to not work with them correctly.

### Impact:

The present `BaseTxAuthDataVerifier` is incompatible with EIPs as it will mutate their function signatures, and is prone to errors if integrators do not properly introduce the `bytes memory` signature payload as the final argument of their function.

Additionally, the assumption presently introduced will fail to function as expected when multiple dynamic arguments are utilized.

### Example:

```solidity
/**
 * @dev Verifies the authenticity and validity of a transaction's authorization data.
 * This function checks if the transaction signature is valid, has not expired, and is signed by the correct user.
 * It also ensures that the transaction has not been replayed by checking and incrementing the nonce.
 * Emits a {NexeraIDSignatureVerified} event upon successful verification.
 *
 * @param msgData The full calldata including the function selector and arguments.
 * @param userAddress The address of the user who signed the transaction.
 * @param blockExpiration The block number until which the transaction is considered valid.
 * @param _signature The signature of the user authorizing the transaction.
 * @return A boolean value indicating whether the transaction was successfully verified.
 *
 * Requirements:
 * - The current block number must be less than `blockExpiration`.
 * - The signature must be valid and correspond to `userAddress`.
 *
 * Emits a {NexeraIDSignatureVerified} event.
 */
function _verifyTxAuthData(
    bytes calldata msgData,
    address userAddress,
    uint256 blockExpiration,
    bytes memory _signature
) internal returns (bool) {
    /// Decompose msgData into the different parts we want
    bytes calldata argsWithSelector = msgData[:msgData.length -
        _SIGNATURE_OFFSET];
```

### Recommendation:

We advise the signature payload to be injected instead, permitting data to be extracted efficiently and without mutating the top-level function signatures.

In detail, a low-level `assembly` block can extract appended calldata that is not necessarily present in the top-level call, permitting EIP-compliant functions to still impose the authentication system designed by the Nexera Protocol.

**Comment by joelamouche** [comment]
@omniscia-core 

>Additionally, multiple dynamic arguments will be packed in calldata differently, causing the fixed _SIGNATURE_OFFSET reduction to not work with them correctly.

Do you have an example of when this wouldn't work?

I added a second bytes input to our example and it passes the tests:

https://github.com/NexeraProtocol/NexeraIDSigGatingContracts/pull/76

>In detail, a low-level assembly block can extract appended calldata that is not necessarily present in the top-level call, permitting EIP-compliant functions to still impose the authentication system designed by the Nexera Protocol.

We actually used to extract the signature from payload and then we changed to using the input because it looked better for the dev and also it optimized gas.
Here are the code changes: https://github.com/NexeraProtocol/NexeraIDSigGatingContracts/pull/29/files#diff-adb65a319fbca60a08d11f196a0f94717b1992c86782e3d044028344e35a84af
Compare the code from hardhat-contracts/contracts/sigVerifiers/TxAuthDataVerifier.sol and hardhat-contracts/contracts/sigVerifiers/BaseTxAuthDataVerifier.sol

So if we add this back:

```
        /// Decompose msg.data into the different parts we want
        bytes calldata argsWithSelector = msg.data[:msg.data.length -
            BYTES_32_VARIABLE -
            SIGNATURE_OFFSET];
        uint256 _blockExpiration = uint256(
            bytes32(
                msg.data[msg.data.length -
                    BYTES_32_VARIABLE -
                    SIGNATURE_OFFSET:msg.data.length - SIGNATURE_OFFSET]
            )
        );
        bytes calldata _signature = msg.data[msg.data.length -
            SIGNATURE_LENGTH -
            SIGNATURE_SUFFIX:msg.data.length - SIGNATURE_SUFFIX];
```

Would that be better?

We also put the blockExpiration in the input to give more flexibility to the dev. If you think we should remove it from the inputs as well to enable conformity to EIPs, then they would have to put it at the end again.

**Comment by joelamouche** [comment]
Actually there is a problem with extracting blockExpiration ad signature from calldata. For blockExpiration more specifically. We need to take it out of the args if we want to allow conformity to EIPs. But unlike signature, blockExpiration is uint256 of fixed byte length and that means that if there is another bytes input, blockExpiration will not be at the end and we don't know where to extract it from the calldata.

**Comment by pash7ka** [comment]
@joelamouche The problem you've mentioned about position of `blockExpiration` in the calldata is only present if we keep current impementation where we specify `signature` and add a new `blockExpiration` arguments in the function definition.

If we decide to keep our current mechanics, where we add a `bytes` field as the last function argument, we can name it  `verifierData` and define as concatenated `blockExpiration` (32 bytes) and `signature` (60 bytes) - total of 92 bytes, and decode that in our modifier.

If we decide to remove that argument from function signature as suggested by Omnitia,  it's same 92 bytes in the end of calldata.

**Comment by joelamouche** [comment]
@pash7ka That's a good solution Pavel. 
But then it means that users that don't need to conform to an EIP will still have to concatenate blockExpiration+Signature when submitting their call which is not great UX.
This is giving me an idea... We could provide two verification contracts: one that derives blockExpiration  and signature from calldata for projects that want to be EIP compliant and one that takes it from the inputs for project who don't need EIP conformity and want an easy to understand UX.

**Comment by omniscia-core** [comment]
Hey @joelamouche, kindly try to relocate the `signature` payload to another position other than the last one. You will notice that tests will start failing, and this is what the exhibit describes.

Using appended data **is how most protocols work when it comes to these types of authorizations** (i.e. [EIP-2771](https://eips.ethereum.org/EIPS/eip-2771)), and it is the only way to properly introduce `calldata` without mutating function signatures. 

The `blockExpiration` introduction will bear no effect on the solution selected as it would simply mean the length that your code needs to account for will need to be increased by `32` bytes (i.e. you can use the same dynamic argument).

**Comment by pash7ka** [comment]
@joelamouche If we do it - have 2 version of this contracts - probably it will be a good idea to have one version work as suggested by Omniscia, and another version - require both `signature` and `blockExpiration` to be passed to the modifier as arguments, so that we don't need to require them to have any specific position in the calldata, but explicitly show them in the function definition.

**Comment by joelamouche** [comment]
@pash7ka yes I would put them in the argument. But signature still has to be in the end because of the way we ask the user to sign the calldata without the signature (and if the signature is not at the end we don't know how to remove it from what will be signed)

**Comment by pash7ka** [comment]
> if the signature is not at the end we don't know how to remove it from what will be signed)

Yeah... you are right here.

**Comment by joelamouche** [comment]
Okay so we came to the conclusion that we will only update the contract to follow @omniscia-core 's suggestions and not make a second version of the contract because using x.offset on chain and doing the same kind of work off-chain to create the data to be signed is too complex for our timeline.
